// Raises IPHONEOS_DEPLOYMENT_TARGET on every CocoaPods target (including
// resource-bundle targets such as the Stripe*Bundle ones from
// @stripe/stripe-react-native) to at least the app's minimum. Xcode 27 rejects
// pod targets below iOS 15.0. app/ios is regenerated by `expo prebuild`, so the
// Podfile patch lives here. Runs after Expo's react_native_post_install.
const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# withPodsDeploymentTarget';

const SNIPPET = `
    ${MARKER}
    min_target = (podfile_properties['ios.deploymentTarget'] || '16.4').to_f
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        current = c.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current.nil? || current.to_f < min_target
          c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_target.to_s
        end
      end
    end
`;

module.exports = function withPodsDeploymentTarget(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const file = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let src = fs.readFileSync(file, 'utf8');
      if (src.includes(MARKER)) return cfg;
      const re = /(react_native_post_install\([\s\S]*?\n\s*\)\n)/;
      if (!re.test(src)) {
        throw new Error('withPodsDeploymentTarget: react_native_post_install block not found in Podfile');
      }
      src = src.replace(re, (m) => m + SNIPPET);
      fs.writeFileSync(file, src);
      return cfg;
    },
  ]);
};
