export type Sport = {
  id: string;
  name: string;
  emoji: string;
  leagues: League[];
};

export type League = {
  id: string;
  name: string;
  country: string;
  /** 'league' = ongoing table; 'cup' = knockout competition; 'international' = national teams. */
  kind?: 'league' | 'cup' | 'international';
  teams: Team[];
};

export type Team = {
  id: string;
  name: string;
  shortName: string;
  city?: string;
};

export const SPORTS: Sport[] = [
  // ─── American Football ────────────────────────────────────────────────────
  {
    id: 'american-football',
    name: 'American Football',
    emoji: '🏈',
    leagues: [
      {
        id: 'nfl',
        name: 'NFL',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'ari', name: 'Arizona Cardinals', shortName: 'Cardinals', city: 'Arizona' },
          { id: 'atl', name: 'Atlanta Falcons', shortName: 'Falcons', city: 'Atlanta' },
          { id: 'bal', name: 'Baltimore Ravens', shortName: 'Ravens', city: 'Baltimore' },
          { id: 'buf', name: 'Buffalo Bills', shortName: 'Bills', city: 'Buffalo' },
          { id: 'car', name: 'Carolina Panthers', shortName: 'Panthers', city: 'Carolina' },
          { id: 'chi', name: 'Chicago Bears', shortName: 'Bears', city: 'Chicago' },
          { id: 'cin', name: 'Cincinnati Bengals', shortName: 'Bengals', city: 'Cincinnati' },
          { id: 'cle', name: 'Cleveland Browns', shortName: 'Browns', city: 'Cleveland' },
          { id: 'dal', name: 'Dallas Cowboys', shortName: 'Cowboys', city: 'Dallas' },
          { id: 'den', name: 'Denver Broncos', shortName: 'Broncos', city: 'Denver' },
          { id: 'det', name: 'Detroit Lions', shortName: 'Lions', city: 'Detroit' },
          { id: 'gb', name: 'Green Bay Packers', shortName: 'Packers', city: 'Green Bay' },
          { id: 'hou', name: 'Houston Texans', shortName: 'Texans', city: 'Houston' },
          { id: 'ind', name: 'Indianapolis Colts', shortName: 'Colts', city: 'Indianapolis' },
          { id: 'jax', name: 'Jacksonville Jaguars', shortName: 'Jaguars', city: 'Jacksonville' },
          { id: 'kc', name: 'Kansas City Chiefs', shortName: 'Chiefs', city: 'Kansas City' },
          { id: 'lv', name: 'Las Vegas Raiders', shortName: 'Raiders', city: 'Las Vegas' },
          { id: 'lac', name: 'Los Angeles Chargers', shortName: 'Chargers', city: 'Los Angeles' },
          { id: 'lar', name: 'Los Angeles Rams', shortName: 'Rams', city: 'Los Angeles' },
          { id: 'mia', name: 'Miami Dolphins', shortName: 'Dolphins', city: 'Miami' },
          { id: 'min', name: 'Minnesota Vikings', shortName: 'Vikings', city: 'Minnesota' },
          { id: 'ne', name: 'New England Patriots', shortName: 'Patriots', city: 'New England' },
          { id: 'no', name: 'New Orleans Saints', shortName: 'Saints', city: 'New Orleans' },
          { id: 'nyg', name: 'New York Giants', shortName: 'Giants', city: 'New York' },
          { id: 'nyj', name: 'New York Jets', shortName: 'Jets', city: 'New York' },
          { id: 'phi', name: 'Philadelphia Eagles', shortName: 'Eagles', city: 'Philadelphia' },
          { id: 'pit', name: 'Pittsburgh Steelers', shortName: 'Steelers', city: 'Pittsburgh' },
          { id: 'sf', name: 'San Francisco 49ers', shortName: '49ers', city: 'San Francisco' },
          { id: 'sea', name: 'Seattle Seahawks', shortName: 'Seahawks', city: 'Seattle' },
          { id: 'tb', name: 'Tampa Bay Buccaneers', shortName: 'Buccaneers', city: 'Tampa Bay' },
          { id: 'ten', name: 'Tennessee Titans', shortName: 'Titans', city: 'Tennessee' },
          { id: 'was', name: 'Washington Commanders', shortName: 'Commanders', city: 'Washington' },
        ],
      },
      {
        id: 'nfl-playoffs',
        name: 'Super Bowl & Playoffs',
        country: 'USA',
        kind: 'cup',
        teams: [
          { id: 'sb-afc', name: 'AFC Championship', shortName: 'AFC Champ' },
          { id: 'sb-nfc', name: 'NFC Championship', shortName: 'NFC Champ' },
          { id: 'sb-game', name: 'Super Bowl', shortName: 'Super Bowl' },
          { id: 'sb-pro', name: 'Pro Bowl', shortName: 'Pro Bowl' },
        ],
      },
      {
        id: 'ncaaf',
        name: 'College Football (NCAA)',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'cfb-ala', name: 'Alabama Crimson Tide', shortName: 'Alabama' },
          { id: 'cfb-uga', name: 'Georgia Bulldogs', shortName: 'Georgia' },
          { id: 'cfb-osu', name: 'Ohio State Buckeyes', shortName: 'Ohio State' },
          { id: 'cfb-mich', name: 'Michigan Wolverines', shortName: 'Michigan' },
          { id: 'cfb-tex', name: 'Texas Longhorns', shortName: 'Texas' },
          { id: 'cfb-nd', name: 'Notre Dame Fighting Irish', shortName: 'Notre Dame' },
          { id: 'cfb-clem', name: 'Clemson Tigers', shortName: 'Clemson' },
          { id: 'cfb-lsu', name: 'LSU Tigers', shortName: 'LSU' },
          { id: 'cfb-ore', name: 'Oregon Ducks', shortName: 'Oregon' },
          { id: 'cfb-usc', name: 'USC Trojans', shortName: 'USC' },
          { id: 'cfb-okla', name: 'Oklahoma Sooners', shortName: 'Oklahoma' },
          { id: 'cfb-psu', name: 'Penn State Nittany Lions', shortName: 'Penn State' },
          { id: 'cfb-fsu', name: 'Florida State Seminoles', shortName: 'Florida State' },
          { id: 'cfb-tenn', name: 'Tennessee Volunteers', shortName: 'Tennessee' },
        ],
      },
      {
        id: 'cfp',
        name: 'College Football Playoff',
        country: 'USA',
        kind: 'cup',
        teams: [
          { id: 'cfp-natty', name: 'National Championship', shortName: 'Natty' },
          { id: 'cfp-rose', name: 'Rose Bowl', shortName: 'Rose Bowl' },
          { id: 'cfp-sugar', name: 'Sugar Bowl', shortName: 'Sugar Bowl' },
          { id: 'cfp-orange', name: 'Orange Bowl', shortName: 'Orange Bowl' },
          { id: 'cfp-cotton', name: 'Cotton Bowl', shortName: 'Cotton Bowl' },
        ],
      },
    ],
  },

  // ─── Basketball ───────────────────────────────────────────────────────────
  {
    id: 'basketball',
    name: 'Basketball',
    emoji: '🏀',
    leagues: [
      {
        id: 'nba',
        name: 'NBA',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'atl-h', name: 'Atlanta Hawks', shortName: 'Hawks', city: 'Atlanta' },
          { id: 'bos', name: 'Boston Celtics', shortName: 'Celtics', city: 'Boston' },
          { id: 'bkn', name: 'Brooklyn Nets', shortName: 'Nets', city: 'Brooklyn' },
          { id: 'cha', name: 'Charlotte Hornets', shortName: 'Hornets', city: 'Charlotte' },
          { id: 'chi-b', name: 'Chicago Bulls', shortName: 'Bulls', city: 'Chicago' },
          { id: 'cle-c', name: 'Cleveland Cavaliers', shortName: 'Cavaliers', city: 'Cleveland' },
          { id: 'dal-m', name: 'Dallas Mavericks', shortName: 'Mavericks', city: 'Dallas' },
          { id: 'den-n', name: 'Denver Nuggets', shortName: 'Nuggets', city: 'Denver' },
          { id: 'det-p', name: 'Detroit Pistons', shortName: 'Pistons', city: 'Detroit' },
          { id: 'gs', name: 'Golden State Warriors', shortName: 'Warriors', city: 'Golden State' },
          { id: 'hou-r', name: 'Houston Rockets', shortName: 'Rockets', city: 'Houston' },
          { id: 'ind-p', name: 'Indiana Pacers', shortName: 'Pacers', city: 'Indiana' },
          { id: 'lac-c', name: 'LA Clippers', shortName: 'Clippers', city: 'Los Angeles' },
          { id: 'lal', name: 'Los Angeles Lakers', shortName: 'Lakers', city: 'Los Angeles' },
          { id: 'mem', name: 'Memphis Grizzlies', shortName: 'Grizzlies', city: 'Memphis' },
          { id: 'mia-h', name: 'Miami Heat', shortName: 'Heat', city: 'Miami' },
          { id: 'mil', name: 'Milwaukee Bucks', shortName: 'Bucks', city: 'Milwaukee' },
          { id: 'min-t', name: 'Minnesota Timberwolves', shortName: 'Timberwolves', city: 'Minnesota' },
          { id: 'no-p', name: 'New Orleans Pelicans', shortName: 'Pelicans', city: 'New Orleans' },
          { id: 'nyk', name: 'New York Knicks', shortName: 'Knicks', city: 'New York' },
          { id: 'okc', name: 'Oklahoma City Thunder', shortName: 'Thunder', city: 'Oklahoma City' },
          { id: 'orl', name: 'Orlando Magic', shortName: 'Magic', city: 'Orlando' },
          { id: 'phi-s', name: 'Philadelphia 76ers', shortName: '76ers', city: 'Philadelphia' },
          { id: 'phx', name: 'Phoenix Suns', shortName: 'Suns', city: 'Phoenix' },
          { id: 'por', name: 'Portland Trail Blazers', shortName: 'Trail Blazers', city: 'Portland' },
          { id: 'sac', name: 'Sacramento Kings', shortName: 'Kings', city: 'Sacramento' },
          { id: 'sa', name: 'San Antonio Spurs', shortName: 'Spurs', city: 'San Antonio' },
          { id: 'tor', name: 'Toronto Raptors', shortName: 'Raptors', city: 'Toronto' },
          { id: 'uta', name: 'Utah Jazz', shortName: 'Jazz', city: 'Utah' },
          { id: 'was-w', name: 'Washington Wizards', shortName: 'Wizards', city: 'Washington' },
        ],
      },
      {
        id: 'nba-playoffs',
        name: 'NBA Playoffs & Finals',
        country: 'USA',
        kind: 'cup',
        teams: [
          { id: 'nbap-finals', name: 'NBA Finals', shortName: 'Finals' },
          { id: 'nbap-ecf', name: 'Eastern Conference Finals', shortName: 'ECF' },
          { id: 'nbap-wcf', name: 'Western Conference Finals', shortName: 'WCF' },
          { id: 'nbap-asg', name: 'NBA All-Star Game', shortName: 'All-Star' },
          { id: 'nbap-itt', name: 'NBA In-Season Tournament', shortName: 'NBA Cup' },
        ],
      },
      {
        id: 'wnba',
        name: 'WNBA',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'wnba-lv', name: 'Las Vegas Aces', shortName: 'Aces', city: 'Las Vegas' },
          { id: 'wnba-ny', name: 'New York Liberty', shortName: 'Liberty', city: 'New York' },
          { id: 'wnba-con', name: 'Connecticut Sun', shortName: 'Sun', city: 'Connecticut' },
          { id: 'wnba-sea', name: 'Seattle Storm', shortName: 'Storm', city: 'Seattle' },
          { id: 'wnba-chi', name: 'Chicago Sky', shortName: 'Sky', city: 'Chicago' },
          { id: 'wnba-ind', name: 'Indiana Fever', shortName: 'Fever', city: 'Indiana' },
          { id: 'wnba-phx', name: 'Phoenix Mercury', shortName: 'Mercury', city: 'Phoenix' },
          { id: 'wnba-min', name: 'Minnesota Lynx', shortName: 'Lynx', city: 'Minnesota' },
        ],
      },
      {
        id: 'ncaab',
        name: 'College Basketball (March Madness)',
        country: 'USA',
        kind: 'cup',
        teams: [
          { id: 'cbb-duke', name: 'Duke Blue Devils', shortName: 'Duke' },
          { id: 'cbb-unc', name: 'North Carolina Tar Heels', shortName: 'UNC' },
          { id: 'cbb-uk', name: 'Kentucky Wildcats', shortName: 'Kentucky' },
          { id: 'cbb-kan', name: 'Kansas Jayhawks', shortName: 'Kansas' },
          { id: 'cbb-uconn', name: 'UConn Huskies', shortName: 'UConn' },
          { id: 'cbb-gonz', name: 'Gonzaga Bulldogs', shortName: 'Gonzaga' },
          { id: 'cbb-ff', name: 'Final Four', shortName: 'Final Four' },
          { id: 'cbb-champ', name: 'NCAA Championship', shortName: 'Championship' },
        ],
      },
      {
        id: 'euroleague',
        name: 'EuroLeague',
        country: 'Europe',
        kind: 'league',
        teams: [
          { id: 'el-rm', name: 'Real Madrid Baloncesto', shortName: 'Real Madrid', city: 'Madrid' },
          { id: 'el-bar', name: 'FC Barcelona Bàsquet', shortName: 'Barcelona', city: 'Barcelona' },
          { id: 'el-pan', name: 'Panathinaikos', shortName: 'Panathinaikos', city: 'Athens' },
          { id: 'el-oly', name: 'Olympiacos', shortName: 'Olympiacos', city: 'Piraeus' },
          { id: 'el-fen', name: 'Fenerbahçe', shortName: 'Fenerbahçe', city: 'Istanbul' },
          { id: 'el-cska', name: 'Maccabi Tel Aviv', shortName: 'Maccabi', city: 'Tel Aviv' },
          { id: 'el-mil', name: 'Olimpia Milano', shortName: 'Milano', city: 'Milan' },
          { id: 'el-bay', name: 'Bayern Munich', shortName: 'Bayern', city: 'Munich' },
          { id: 'el-final4', name: 'EuroLeague Final Four', shortName: 'Final Four' },
        ],
      },
      {
        id: 'fiba',
        name: 'FIBA World Cup & Olympics',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'fiba-usa', name: 'USA', shortName: 'USA' },
          { id: 'fiba-esp', name: 'Spain', shortName: 'Spain' },
          { id: 'fiba-fra', name: 'France', shortName: 'France' },
          { id: 'fiba-srb', name: 'Serbia', shortName: 'Serbia' },
          { id: 'fiba-aus', name: 'Australia', shortName: 'Australia' },
          { id: 'fiba-can', name: 'Canada', shortName: 'Canada' },
          { id: 'fiba-ger', name: 'Germany', shortName: 'Germany' },
          { id: 'fiba-gre', name: 'Greece', shortName: 'Greece' },
        ],
      },
    ],
  },

  // ─── Baseball ─────────────────────────────────────────────────────────────
  {
    id: 'baseball',
    name: 'Baseball',
    emoji: '⚾',
    leagues: [
      {
        id: 'mlb',
        name: 'MLB',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'ari-d', name: 'Arizona Diamondbacks', shortName: 'D-backs', city: 'Arizona' },
          { id: 'atl-b', name: 'Atlanta Braves', shortName: 'Braves', city: 'Atlanta' },
          { id: 'bal-o', name: 'Baltimore Orioles', shortName: 'Orioles', city: 'Baltimore' },
          { id: 'bos-s', name: 'Boston Red Sox', shortName: 'Red Sox', city: 'Boston' },
          { id: 'chi-c', name: 'Chicago Cubs', shortName: 'Cubs', city: 'Chicago' },
          { id: 'chi-w', name: 'Chicago White Sox', shortName: 'White Sox', city: 'Chicago' },
          { id: 'cin-r', name: 'Cincinnati Reds', shortName: 'Reds', city: 'Cincinnati' },
          { id: 'cle-g', name: 'Cleveland Guardians', shortName: 'Guardians', city: 'Cleveland' },
          { id: 'col', name: 'Colorado Rockies', shortName: 'Rockies', city: 'Colorado' },
          { id: 'det-t', name: 'Detroit Tigers', shortName: 'Tigers', city: 'Detroit' },
          { id: 'hou-a', name: 'Houston Astros', shortName: 'Astros', city: 'Houston' },
          { id: 'kc-r', name: 'Kansas City Royals', shortName: 'Royals', city: 'Kansas City' },
          { id: 'la-d', name: 'Los Angeles Dodgers', shortName: 'Dodgers', city: 'Los Angeles' },
          { id: 'la-a', name: 'Los Angeles Angels', shortName: 'Angels', city: 'Los Angeles' },
          { id: 'mia-m', name: 'Miami Marlins', shortName: 'Marlins', city: 'Miami' },
          { id: 'mil-b', name: 'Milwaukee Brewers', shortName: 'Brewers', city: 'Milwaukee' },
          { id: 'min-t2', name: 'Minnesota Twins', shortName: 'Twins', city: 'Minnesota' },
          { id: 'nym', name: 'New York Mets', shortName: 'Mets', city: 'New York' },
          { id: 'nyy', name: 'New York Yankees', shortName: 'Yankees', city: 'New York' },
          { id: 'oak', name: 'Athletics', shortName: 'Athletics', city: 'Oakland' },
          { id: 'phi-p', name: 'Philadelphia Phillies', shortName: 'Phillies', city: 'Philadelphia' },
          { id: 'pit-p', name: 'Pittsburgh Pirates', shortName: 'Pirates', city: 'Pittsburgh' },
          { id: 'sd', name: 'San Diego Padres', shortName: 'Padres', city: 'San Diego' },
          { id: 'sf-g', name: 'San Francisco Giants', shortName: 'Giants', city: 'San Francisco' },
          { id: 'sea-m', name: 'Seattle Mariners', shortName: 'Mariners', city: 'Seattle' },
          { id: 'stl', name: 'St. Louis Cardinals', shortName: 'Cardinals', city: 'St. Louis' },
          { id: 'tb-r', name: 'Tampa Bay Rays', shortName: 'Rays', city: 'Tampa Bay' },
          { id: 'tex', name: 'Texas Rangers', shortName: 'Rangers', city: 'Texas' },
          { id: 'tor-b', name: 'Toronto Blue Jays', shortName: 'Blue Jays', city: 'Toronto' },
          { id: 'was-n', name: 'Washington Nationals', shortName: 'Nationals', city: 'Washington' },
        ],
      },
      {
        id: 'mlb-postseason',
        name: 'World Series & Playoffs',
        country: 'USA',
        kind: 'cup',
        teams: [
          { id: 'ws-game', name: 'World Series', shortName: 'World Series' },
          { id: 'ws-alcs', name: 'ALCS', shortName: 'ALCS' },
          { id: 'ws-nlcs', name: 'NLCS', shortName: 'NLCS' },
          { id: 'ws-asg', name: 'MLB All-Star Game', shortName: 'All-Star' },
        ],
      },
      {
        id: 'wbc',
        name: 'World Baseball Classic',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'wbc-usa', name: 'USA', shortName: 'USA' },
          { id: 'wbc-jpn', name: 'Japan', shortName: 'Japan' },
          { id: 'wbc-dom', name: 'Dominican Republic', shortName: 'Dominican Rep.' },
          { id: 'wbc-pur', name: 'Puerto Rico', shortName: 'Puerto Rico' },
          { id: 'wbc-ven', name: 'Venezuela', shortName: 'Venezuela' },
          { id: 'wbc-kor', name: 'South Korea', shortName: 'South Korea' },
          { id: 'wbc-mex', name: 'Mexico', shortName: 'Mexico' },
          { id: 'wbc-cub', name: 'Cuba', shortName: 'Cuba' },
        ],
      },
      {
        id: 'npb',
        name: 'NPB (Japan)',
        country: 'Japan',
        kind: 'league',
        teams: [
          { id: 'npb-gia', name: 'Yomiuri Giants', shortName: 'Giants', city: 'Tokyo' },
          { id: 'npb-tig', name: 'Hanshin Tigers', shortName: 'Tigers', city: 'Osaka' },
          { id: 'npb-haw', name: 'SoftBank Hawks', shortName: 'Hawks', city: 'Fukuoka' },
          { id: 'npb-swa', name: 'Yakult Swallows', shortName: 'Swallows', city: 'Tokyo' },
          { id: 'npb-car', name: 'Hiroshima Carp', shortName: 'Carp', city: 'Hiroshima' },
          { id: 'npb-fig', name: 'Nippon-Ham Fighters', shortName: 'Fighters', city: 'Sapporo' },
        ],
      },
    ],
  },

  // ─── Ice Hockey ───────────────────────────────────────────────────────────
  {
    id: 'ice-hockey',
    name: 'Ice Hockey',
    emoji: '🏒',
    leagues: [
      {
        id: 'nhl',
        name: 'NHL',
        country: 'USA/Canada',
        kind: 'league',
        teams: [
          { id: 'ana', name: 'Anaheim Ducks', shortName: 'Ducks', city: 'Anaheim' },
          { id: 'uta-hc', name: 'Utah Hockey Club', shortName: 'Utah HC', city: 'Utah' },
          { id: 'bos-b', name: 'Boston Bruins', shortName: 'Bruins', city: 'Boston' },
          { id: 'buf-s', name: 'Buffalo Sabres', shortName: 'Sabres', city: 'Buffalo' },
          { id: 'cal', name: 'Calgary Flames', shortName: 'Flames', city: 'Calgary' },
          { id: 'car-h', name: 'Carolina Hurricanes', shortName: 'Hurricanes', city: 'Carolina' },
          { id: 'chi-bh', name: 'Chicago Blackhawks', shortName: 'Blackhawks', city: 'Chicago' },
          { id: 'col-a', name: 'Colorado Avalanche', shortName: 'Avalanche', city: 'Colorado' },
          { id: 'cbj', name: 'Columbus Blue Jackets', shortName: 'Blue Jackets', city: 'Columbus' },
          { id: 'dal-s', name: 'Dallas Stars', shortName: 'Stars', city: 'Dallas' },
          { id: 'det-rw', name: 'Detroit Red Wings', shortName: 'Red Wings', city: 'Detroit' },
          { id: 'edm', name: 'Edmonton Oilers', shortName: 'Oilers', city: 'Edmonton' },
          { id: 'fla', name: 'Florida Panthers', shortName: 'Panthers', city: 'Florida' },
          { id: 'lak', name: 'Los Angeles Kings', shortName: 'Kings', city: 'Los Angeles' },
          { id: 'min-w', name: 'Minnesota Wild', shortName: 'Wild', city: 'Minnesota' },
          { id: 'mtl', name: 'Montreal Canadiens', shortName: 'Canadiens', city: 'Montreal' },
          { id: 'nsh', name: 'Nashville Predators', shortName: 'Predators', city: 'Nashville' },
          { id: 'njd', name: 'New Jersey Devils', shortName: 'Devils', city: 'New Jersey' },
          { id: 'nyi', name: 'New York Islanders', shortName: 'Islanders', city: 'New York' },
          { id: 'nyr', name: 'New York Rangers', shortName: 'Rangers', city: 'New York' },
          { id: 'ott', name: 'Ottawa Senators', shortName: 'Senators', city: 'Ottawa' },
          { id: 'phi-f', name: 'Philadelphia Flyers', shortName: 'Flyers', city: 'Philadelphia' },
          { id: 'pit-p2', name: 'Pittsburgh Penguins', shortName: 'Penguins', city: 'Pittsburgh' },
          { id: 'sjsh', name: 'San Jose Sharks', shortName: 'Sharks', city: 'San Jose' },
          { id: 'sea-k', name: 'Seattle Kraken', shortName: 'Kraken', city: 'Seattle' },
          { id: 'stl-b', name: 'St. Louis Blues', shortName: 'Blues', city: 'St. Louis' },
          { id: 'tbl', name: 'Tampa Bay Lightning', shortName: 'Lightning', city: 'Tampa Bay' },
          { id: 'tor-ml', name: 'Toronto Maple Leafs', shortName: 'Maple Leafs', city: 'Toronto' },
          { id: 'van', name: 'Vancouver Canucks', shortName: 'Canucks', city: 'Vancouver' },
          { id: 'vgk', name: 'Vegas Golden Knights', shortName: 'Golden Knights', city: 'Vegas' },
          { id: 'was-c', name: 'Washington Capitals', shortName: 'Capitals', city: 'Washington' },
          { id: 'wpg', name: 'Winnipeg Jets', shortName: 'Jets', city: 'Winnipeg' },
        ],
      },
      {
        id: 'stanley-cup',
        name: 'Stanley Cup Playoffs',
        country: 'USA/Canada',
        kind: 'cup',
        teams: [
          { id: 'sc-final', name: 'Stanley Cup Final', shortName: 'SC Final' },
          { id: 'sc-ecf', name: 'Eastern Conference Final', shortName: 'ECF' },
          { id: 'sc-wcf', name: 'Western Conference Final', shortName: 'WCF' },
          { id: 'sc-winter', name: 'Winter Classic', shortName: 'Winter Classic' },
        ],
      },
      {
        id: 'iihf',
        name: 'IIHF World Championship & Olympics',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'iihf-can', name: 'Canada', shortName: 'Canada' },
          { id: 'iihf-usa', name: 'USA', shortName: 'USA' },
          { id: 'iihf-fin', name: 'Finland', shortName: 'Finland' },
          { id: 'iihf-swe', name: 'Sweden', shortName: 'Sweden' },
          { id: 'iihf-cze', name: 'Czechia', shortName: 'Czechia' },
          { id: 'iihf-sui', name: 'Switzerland', shortName: 'Switzerland' },
          { id: 'iihf-ger', name: 'Germany', shortName: 'Germany' },
          { id: 'iihf-svk', name: 'Slovakia', shortName: 'Slovakia' },
        ],
      },
    ],
  },

  // ─── Soccer / Football ────────────────────────────────────────────────────
  {
    id: 'soccer',
    name: 'Soccer',
    emoji: '⚽',
    leagues: [
      {
        id: 'premier-league',
        name: 'Premier League',
        country: 'England',
        kind: 'league',
        teams: [
          { id: 'ars', name: 'Arsenal', shortName: 'Arsenal', city: 'London' },
          { id: 'avl', name: 'Aston Villa', shortName: 'Villa', city: 'Birmingham' },
          { id: 'bou', name: 'Bournemouth', shortName: 'Bournemouth', city: 'Bournemouth' },
          { id: 'bre', name: 'Brentford', shortName: 'Brentford', city: 'London' },
          { id: 'bha', name: 'Brighton', shortName: 'Brighton', city: 'Brighton' },
          { id: 'che', name: 'Chelsea', shortName: 'Chelsea', city: 'London' },
          { id: 'cry', name: 'Crystal Palace', shortName: 'Palace', city: 'London' },
          { id: 'eve', name: 'Everton', shortName: 'Everton', city: 'Liverpool' },
          { id: 'ful', name: 'Fulham', shortName: 'Fulham', city: 'London' },
          { id: 'ips', name: 'Ipswich Town', shortName: 'Ipswich', city: 'Ipswich' },
          { id: 'lei', name: 'Leicester City', shortName: 'Leicester', city: 'Leicester' },
          { id: 'liv', name: 'Liverpool', shortName: 'Liverpool', city: 'Liverpool' },
          { id: 'mci', name: 'Manchester City', shortName: 'Man City', city: 'Manchester' },
          { id: 'mun', name: 'Manchester United', shortName: 'Man Utd', city: 'Manchester' },
          { id: 'new', name: 'Newcastle United', shortName: 'Newcastle', city: 'Newcastle' },
          { id: 'nfo', name: 'Nottingham Forest', shortName: "Nott'm Forest", city: 'Nottingham' },
          { id: 'sou', name: 'Southampton', shortName: 'Southampton', city: 'Southampton' },
          { id: 'tot', name: 'Tottenham Hotspur', shortName: 'Spurs', city: 'London' },
          { id: 'whu', name: 'West Ham United', shortName: 'West Ham', city: 'London' },
          { id: 'wol', name: 'Wolverhampton Wanderers', shortName: 'Wolves', city: 'Wolverhampton' },
        ],
      },
      {
        id: 'efl-championship',
        name: 'EFL Championship',
        country: 'England',
        kind: 'league',
        teams: [
          { id: 'ch-lee', name: 'Leeds United', shortName: 'Leeds', city: 'Leeds' },
          { id: 'ch-bur', name: 'Burnley', shortName: 'Burnley', city: 'Burnley' },
          { id: 'ch-shu', name: 'Sheffield United', shortName: 'Sheff Utd', city: 'Sheffield' },
          { id: 'ch-sun', name: 'Sunderland', shortName: 'Sunderland', city: 'Sunderland' },
          { id: 'ch-wba', name: 'West Bromwich Albion', shortName: 'West Brom', city: 'West Bromwich' },
          { id: 'ch-mid', name: 'Middlesbrough', shortName: 'Boro', city: 'Middlesbrough' },
          { id: 'ch-nor', name: 'Norwich City', shortName: 'Norwich', city: 'Norwich' },
          { id: 'ch-cov', name: 'Coventry City', shortName: 'Coventry', city: 'Coventry' },
          { id: 'ch-wat', name: 'Watford', shortName: 'Watford', city: 'Watford' },
          { id: 'ch-hul', name: 'Hull City', shortName: 'Hull', city: 'Hull' },
          { id: 'ch-black', name: 'Blackburn Rovers', shortName: 'Blackburn', city: 'Blackburn' },
          { id: 'ch-bri', name: 'Bristol City', shortName: 'Bristol City', city: 'Bristol' },
        ],
      },
      {
        id: 'la-liga',
        name: 'La Liga',
        country: 'Spain',
        kind: 'league',
        teams: [
          { id: 'ath', name: 'Athletic Club', shortName: 'Athletic', city: 'Bilbao' },
          { id: 'atm', name: 'Atlético Madrid', shortName: 'Atleti', city: 'Madrid' },
          { id: 'bar', name: 'FC Barcelona', shortName: 'Barça', city: 'Barcelona' },
          { id: 'bet', name: 'Real Betis', shortName: 'Betis', city: 'Seville' },
          { id: 'cel', name: 'Celta Vigo', shortName: 'Celta', city: 'Vigo' },
          { id: 'esh', name: 'Espanyol', shortName: 'Espanyol', city: 'Barcelona' },
          { id: 'gir', name: 'Girona', shortName: 'Girona', city: 'Girona' },
          { id: 'get', name: 'Getafe', shortName: 'Getafe', city: 'Getafe' },
          { id: 'las', name: 'Las Palmas', shortName: 'Las Palmas', city: 'Las Palmas' },
          { id: 'leg', name: 'Leganés', shortName: 'Leganés', city: 'Leganés' },
          { id: 'may', name: 'Mallorca', shortName: 'Mallorca', city: 'Palma' },
          { id: 'osa', name: 'Osasuna', shortName: 'Osasuna', city: 'Pamplona' },
          { id: 'rayo', name: 'Rayo Vallecano', shortName: 'Rayo', city: 'Madrid' },
          { id: 'rm', name: 'Real Madrid', shortName: 'Real Madrid', city: 'Madrid' },
          { id: 'rso', name: 'Real Sociedad', shortName: 'Sociedad', city: 'San Sebastián' },
          { id: 'rva', name: 'Real Valladolid', shortName: 'Valladolid', city: 'Valladolid' },
          { id: 'sev', name: 'Sevilla', shortName: 'Sevilla', city: 'Seville' },
          { id: 'val', name: 'Valencia', shortName: 'Valencia', city: 'Valencia' },
          { id: 'vil', name: 'Villarreal', shortName: 'Villarreal', city: 'Villarreal' },
        ],
      },
      {
        id: 'bundesliga',
        name: 'Bundesliga',
        country: 'Germany',
        kind: 'league',
        teams: [
          { id: 'b04', name: 'Bayer Leverkusen', shortName: 'Leverkusen', city: 'Leverkusen' },
          { id: 'bay', name: 'Bayern Munich', shortName: 'Bayern', city: 'Munich' },
          { id: 'boc', name: 'VfL Bochum', shortName: 'Bochum', city: 'Bochum' },
          { id: 'bre-w', name: 'Werder Bremen', shortName: 'Bremen', city: 'Bremen' },
          { id: 'dor', name: 'Borussia Dortmund', shortName: 'Dortmund', city: 'Dortmund' },
          { id: 'ein', name: 'Eintracht Frankfurt', shortName: 'Frankfurt', city: 'Frankfurt' },
          { id: 'fcko', name: 'FC Köln', shortName: 'Köln', city: 'Cologne' },
          { id: 'fre', name: 'SC Freiburg', shortName: 'Freiburg', city: 'Freiburg' },
          { id: 'hei', name: 'TSG Hoffenheim', shortName: 'Hoffenheim', city: 'Hoffenheim' },
          { id: 'hol', name: 'Holstein Kiel', shortName: 'Kiel', city: 'Kiel' },
          { id: 'mgl', name: 'Borussia Mönchengladbach', shortName: 'Gladbach', city: 'Mönchengladbach' },
          { id: 'mnz', name: 'Mainz 05', shortName: 'Mainz', city: 'Mainz' },
          { id: 'rb', name: 'RB Leipzig', shortName: 'Leipzig', city: 'Leipzig' },
          { id: 'stut', name: 'VfB Stuttgart', shortName: 'Stuttgart', city: 'Stuttgart' },
          { id: 'ubs', name: 'Union Berlin', shortName: 'Union Berlin', city: 'Berlin' },
          { id: 'aug', name: 'FC Augsburg', shortName: 'Augsburg', city: 'Augsburg' },
          { id: 'hei-fc', name: '1. FC Heidenheim', shortName: 'Heidenheim', city: 'Heidenheim' },
          { id: 'wol-vfl', name: 'VfL Wolfsburg', shortName: 'Wolfsburg', city: 'Wolfsburg' },
        ],
      },
      {
        id: 'serie-a',
        name: 'Serie A',
        country: 'Italy',
        kind: 'league',
        teams: [
          { id: 'ata', name: 'Atalanta', shortName: 'Atalanta', city: 'Bergamo' },
          { id: 'bol', name: 'Bologna', shortName: 'Bologna', city: 'Bologna' },
          { id: 'cag', name: 'Cagliari', shortName: 'Cagliari', city: 'Cagliari' },
          { id: 'com', name: 'Como', shortName: 'Como', city: 'Como' },
          { id: 'emp', name: 'Empoli', shortName: 'Empoli', city: 'Empoli' },
          { id: 'fio', name: 'Fiorentina', shortName: 'Fiorentina', city: 'Florence' },
          { id: 'gen', name: 'Genoa', shortName: 'Genoa', city: 'Genoa' },
          { id: 'hel', name: 'Hellas Verona', shortName: 'Verona', city: 'Verona' },
          { id: 'int', name: 'Inter Milan', shortName: 'Inter', city: 'Milan' },
          { id: 'juv', name: 'Juventus', shortName: 'Juve', city: 'Turin' },
          { id: 'laz', name: 'Lazio', shortName: 'Lazio', city: 'Rome' },
          { id: 'lec', name: 'Lecce', shortName: 'Lecce', city: 'Lecce' },
          { id: 'acm', name: 'AC Milan', shortName: 'Milan', city: 'Milan' },
          { id: 'mon', name: 'Monza', shortName: 'Monza', city: 'Monza' },
          { id: 'nap', name: 'Napoli', shortName: 'Napoli', city: 'Naples' },
          { id: 'par', name: 'Parma', shortName: 'Parma', city: 'Parma' },
          { id: 'rom', name: 'AS Roma', shortName: 'Roma', city: 'Rome' },
          { id: 'tor-fc', name: 'Torino', shortName: 'Torino', city: 'Turin' },
          { id: 'udi', name: 'Udinese', shortName: 'Udinese', city: 'Udine' },
          { id: 'ven', name: 'Venezia', shortName: 'Venezia', city: 'Venice' },
        ],
      },
      {
        id: 'ligue-1',
        name: 'Ligue 1',
        country: 'France',
        kind: 'league',
        teams: [
          { id: 'ang', name: 'Angers SCO', shortName: 'Angers', city: 'Angers' },
          { id: 'asm', name: 'AS Monaco', shortName: 'Monaco', city: 'Monaco' },
          { id: 'ass', name: 'AS Saint-Étienne', shortName: 'Saint-Étienne', city: 'Saint-Étienne' },
          { id: 'aux', name: 'AJ Auxerre', shortName: 'Auxerre', city: 'Auxerre' },
          { id: 'bre-f', name: 'Stade Brestois', shortName: 'Brest', city: 'Brest' },
          { id: 'hac', name: 'Le Havre', shortName: 'Le Havre', city: 'Le Havre' },
          { id: 'len', name: 'RC Lens', shortName: 'Lens', city: 'Lens' },
          { id: 'lil', name: 'LOSC Lille', shortName: 'Lille', city: 'Lille' },
          { id: 'lyn', name: 'Olympique Lyonnais', shortName: 'Lyon', city: 'Lyon' },
          { id: 'mar', name: 'Olympique de Marseille', shortName: 'Marseille', city: 'Marseille' },
          { id: 'mtp', name: 'Montpellier', shortName: 'Montpellier', city: 'Montpellier' },
          { id: 'nan', name: 'FC Nantes', shortName: 'Nantes', city: 'Nantes' },
          { id: 'nic', name: 'OGC Nice', shortName: 'Nice', city: 'Nice' },
          { id: 'psg', name: 'Paris Saint-Germain', shortName: 'PSG', city: 'Paris' },
          { id: 'ren', name: 'Stade Rennais', shortName: 'Rennes', city: 'Rennes' },
          { id: 'str', name: 'RC Strasbourg', shortName: 'Strasbourg', city: 'Strasbourg' },
          { id: 'tou', name: 'Toulouse FC', shortName: 'Toulouse', city: 'Toulouse' },
          { id: 'rei', name: 'Stade de Reims', shortName: 'Reims', city: 'Reims' },
        ],
      },
      {
        id: 'eredivisie',
        name: 'Eredivisie',
        country: 'Netherlands',
        kind: 'league',
        teams: [
          { id: 'aja', name: 'Ajax', shortName: 'Ajax', city: 'Amsterdam' },
          { id: 'psv', name: 'PSV Eindhoven', shortName: 'PSV', city: 'Eindhoven' },
          { id: 'fey', name: 'Feyenoord', shortName: 'Feyenoord', city: 'Rotterdam' },
          { id: 'az', name: 'AZ Alkmaar', shortName: 'AZ', city: 'Alkmaar' },
          { id: 'twe', name: 'FC Twente', shortName: 'Twente', city: 'Enschede' },
          { id: 'utr', name: 'FC Utrecht', shortName: 'Utrecht', city: 'Utrecht' },
          { id: 'ese', name: 'Heerenveen', shortName: 'Heerenveen', city: 'Heerenveen' },
        ],
      },
      {
        id: 'primeira-liga',
        name: 'Primeira Liga',
        country: 'Portugal',
        kind: 'league',
        teams: [
          { id: 'ben', name: 'Benfica', shortName: 'Benfica', city: 'Lisbon' },
          { id: 'por-fc', name: 'FC Porto', shortName: 'Porto', city: 'Porto' },
          { id: 'spo', name: 'Sporting CP', shortName: 'Sporting', city: 'Lisbon' },
          { id: 'bra-sc', name: 'SC Braga', shortName: 'Braga', city: 'Braga' },
          { id: 'vit', name: 'Vitória de Guimarães', shortName: 'Vitória SC', city: 'Guimarães' },
        ],
      },
      {
        id: 'scottish-prem',
        name: 'Scottish Premiership',
        country: 'Scotland',
        kind: 'league',
        teams: [
          { id: 'cel-fc', name: 'Celtic', shortName: 'Celtic', city: 'Glasgow' },
          { id: 'ran', name: 'Rangers', shortName: 'Rangers', city: 'Glasgow' },
          { id: 'abe', name: 'Aberdeen', shortName: 'Aberdeen', city: 'Aberdeen' },
          { id: 'hea', name: 'Heart of Midlothian', shortName: 'Hearts', city: 'Edinburgh' },
          { id: 'hib', name: 'Hibernian', shortName: 'Hibs', city: 'Edinburgh' },
        ],
      },
      {
        id: 'mls',
        name: 'MLS',
        country: 'USA/Canada',
        kind: 'league',
        teams: [
          { id: 'atl-u', name: 'Atlanta United', shortName: 'Atlanta Utd', city: 'Atlanta' },
          { id: 'aus', name: 'Austin FC', shortName: 'Austin FC', city: 'Austin' },
          { id: 'chi-f', name: 'Chicago Fire', shortName: 'Chicago Fire', city: 'Chicago' },
          { id: 'cin-fc', name: 'FC Cincinnati', shortName: 'Cincinnati', city: 'Cincinnati' },
          { id: 'col-r', name: 'Colorado Rapids', shortName: 'Colorado', city: 'Colorado' },
          { id: 'col-c', name: 'Columbus Crew', shortName: 'Columbus', city: 'Columbus' },
          { id: 'dal-fc', name: 'FC Dallas', shortName: 'FC Dallas', city: 'Dallas' },
          { id: 'dc', name: 'D.C. United', shortName: 'DC United', city: 'Washington' },
          { id: 'hou-d', name: 'Houston Dynamo', shortName: 'Houston', city: 'Houston' },
          { id: 'int-mia', name: 'Inter Miami', shortName: 'Inter Miami', city: 'Miami' },
          { id: 'la-fc', name: 'LAFC', shortName: 'LAFC', city: 'Los Angeles' },
          { id: 'la-g', name: 'LA Galaxy', shortName: 'LA Galaxy', city: 'Los Angeles' },
          { id: 'min-u', name: 'Minnesota United', shortName: 'Minnesota', city: 'Minnesota' },
          { id: 'cf-mtl', name: 'CF Montréal', shortName: 'Montréal', city: 'Montreal' },
          { id: 'nas', name: 'Nashville SC', shortName: 'Nashville', city: 'Nashville' },
          { id: 'ne-r', name: 'New England Revolution', shortName: 'New England', city: 'Boston' },
          { id: 'nyc', name: 'New York City FC', shortName: 'NYCFC', city: 'New York' },
          { id: 'nyrb', name: 'New York Red Bulls', shortName: 'NY Red Bulls', city: 'New York' },
          { id: 'orl-c', name: 'Orlando City', shortName: 'Orlando', city: 'Orlando' },
          { id: 'phi-u', name: 'Philadelphia Union', shortName: 'Philadelphia', city: 'Philadelphia' },
          { id: 'por-t', name: 'Portland Timbers', shortName: 'Portland', city: 'Portland' },
          { id: 'rsl', name: 'Real Salt Lake', shortName: 'Salt Lake', city: 'Salt Lake City' },
          { id: 'sjea', name: 'San Jose Earthquakes', shortName: 'San Jose', city: 'San Jose' },
          { id: 'sea-s', name: 'Seattle Sounders', shortName: 'Seattle', city: 'Seattle' },
          { id: 'skc', name: 'Sporting Kansas City', shortName: 'Sporting KC', city: 'Kansas City' },
          { id: 'st-l', name: 'St. Louis City SC', shortName: 'St. Louis', city: 'St. Louis' },
          { id: 'tor-fc2', name: 'Toronto FC', shortName: 'Toronto', city: 'Toronto' },
          { id: 'van-wh', name: 'Vancouver Whitecaps', shortName: 'Vancouver', city: 'Vancouver' },
        ],
      },
      {
        id: 'liga-mx',
        name: 'Liga MX',
        country: 'Mexico',
        kind: 'league',
        teams: [
          { id: 'ame', name: 'Club América', shortName: 'América', city: 'Mexico City' },
          { id: 'gua', name: 'Chivas Guadalajara', shortName: 'Chivas', city: 'Guadalajara' },
          { id: 'cru', name: 'Cruz Azul', shortName: 'Cruz Azul', city: 'Mexico City' },
          { id: 'pum', name: 'Pumas UNAM', shortName: 'Pumas', city: 'Mexico City' },
          { id: 'mty', name: 'Monterrey', shortName: 'Monterrey', city: 'Monterrey' },
          { id: 'tig', name: 'Tigres UANL', shortName: 'Tigres', city: 'Monterrey' },
          { id: 'tol', name: 'Toluca', shortName: 'Toluca', city: 'Toluca' },
          { id: 'san-l', name: 'Santos Laguna', shortName: 'Santos', city: 'Torreón' },
        ],
      },
      {
        id: 'brasileirao',
        name: 'Brasileirão Série A',
        country: 'Brazil',
        kind: 'league',
        teams: [
          { id: 'bra-fla', name: 'Flamengo', shortName: 'Flamengo', city: 'Rio de Janeiro' },
          { id: 'pal', name: 'Palmeiras', shortName: 'Palmeiras', city: 'São Paulo' },
          { id: 'spo-fc', name: 'São Paulo', shortName: 'São Paulo', city: 'São Paulo' },
          { id: 'cor', name: 'Corinthians', shortName: 'Corinthians', city: 'São Paulo' },
          { id: 'flu', name: 'Fluminense', shortName: 'Fluminense', city: 'Rio de Janeiro' },
          { id: 'bot', name: 'Botafogo', shortName: 'Botafogo', city: 'Rio de Janeiro' },
          { id: 'gre', name: 'Grêmio', shortName: 'Grêmio', city: 'Porto Alegre' },
          { id: 'int-br', name: 'Internacional', shortName: 'Internacional', city: 'Porto Alegre' },
          { id: 'atl-mg', name: 'Atlético Mineiro', shortName: 'Atlético-MG', city: 'Belo Horizonte' },
        ],
      },
      {
        id: 'saudi-pro',
        name: 'Saudi Pro League',
        country: 'Saudi Arabia',
        kind: 'league',
        teams: [
          { id: 'aln', name: 'Al Nassr', shortName: 'Al Nassr', city: 'Riyadh' },
          { id: 'alh', name: 'Al Hilal', shortName: 'Al Hilal', city: 'Riyadh' },
          { id: 'ali', name: 'Al Ittihad', shortName: 'Al Ittihad', city: 'Jeddah' },
          { id: 'ala', name: 'Al Ahli', shortName: 'Al Ahli', city: 'Jeddah' },
        ],
      },
      {
        id: 'ucl',
        name: 'UEFA Champions League',
        country: 'Europe',
        kind: 'cup',
        teams: [
          { id: 'ucl-ars', name: 'Arsenal', shortName: 'Arsenal', city: 'London' },
          { id: 'ucl-atm', name: 'Atlético Madrid', shortName: 'Atleti', city: 'Madrid' },
          { id: 'ucl-bar', name: 'FC Barcelona', shortName: 'Barça', city: 'Barcelona' },
          { id: 'ucl-bay', name: 'Bayern Munich', shortName: 'Bayern', city: 'Munich' },
          { id: 'ucl-bvb', name: 'Borussia Dortmund', shortName: 'Dortmund', city: 'Dortmund' },
          { id: 'ucl-che', name: 'Chelsea', shortName: 'Chelsea', city: 'London' },
          { id: 'ucl-int', name: 'Inter Milan', shortName: 'Inter', city: 'Milan' },
          { id: 'ucl-juv', name: 'Juventus', shortName: 'Juve', city: 'Turin' },
          { id: 'ucl-liv', name: 'Liverpool', shortName: 'Liverpool', city: 'Liverpool' },
          { id: 'ucl-mci', name: 'Manchester City', shortName: 'Man City', city: 'Manchester' },
          { id: 'ucl-mil', name: 'AC Milan', shortName: 'Milan', city: 'Milan' },
          { id: 'ucl-nap', name: 'Napoli', shortName: 'Napoli', city: 'Naples' },
          { id: 'ucl-par', name: 'Paris Saint-Germain', shortName: 'PSG', city: 'Paris' },
          { id: 'ucl-rm', name: 'Real Madrid', shortName: 'Real Madrid', city: 'Madrid' },
          { id: 'ucl-final', name: 'Champions League Final', shortName: 'UCL Final' },
        ],
      },
      {
        id: 'uel',
        name: 'UEFA Europa League',
        country: 'Europe',
        kind: 'cup',
        teams: [
          { id: 'uel-mun', name: 'Manchester United', shortName: 'Man Utd', city: 'Manchester' },
          { id: 'uel-tot', name: 'Tottenham Hotspur', shortName: 'Spurs', city: 'London' },
          { id: 'uel-rom', name: 'AS Roma', shortName: 'Roma', city: 'Rome' },
          { id: 'uel-laz', name: 'Lazio', shortName: 'Lazio', city: 'Rome' },
          { id: 'uel-ath', name: 'Athletic Club', shortName: 'Athletic', city: 'Bilbao' },
          { id: 'uel-lyn', name: 'Olympique Lyonnais', shortName: 'Lyon', city: 'Lyon' },
          { id: 'uel-ajax', name: 'Ajax', shortName: 'Ajax', city: 'Amsterdam' },
          { id: 'uel-por', name: 'FC Porto', shortName: 'Porto', city: 'Porto' },
          { id: 'uel-final', name: 'Europa League Final', shortName: 'UEL Final' },
        ],
      },
      {
        id: 'uecl',
        name: 'UEFA Conference League',
        country: 'Europe',
        kind: 'cup',
        teams: [
          { id: 'uecl-che', name: 'Chelsea', shortName: 'Chelsea', city: 'London' },
          { id: 'uecl-fio', name: 'Fiorentina', shortName: 'Fiorentina', city: 'Florence' },
          { id: 'uecl-ast', name: 'Aston Villa', shortName: 'Villa', city: 'Birmingham' },
          { id: 'uecl-final', name: 'Conference League Final', shortName: 'UECL Final' },
        ],
      },
      {
        id: 'fa-cup',
        name: 'FA Cup',
        country: 'England',
        kind: 'cup',
        teams: [
          { id: 'fac-ars', name: 'Arsenal', shortName: 'Arsenal', city: 'London' },
          { id: 'fac-mun', name: 'Manchester United', shortName: 'Man Utd', city: 'Manchester' },
          { id: 'fac-che', name: 'Chelsea', shortName: 'Chelsea', city: 'London' },
          { id: 'fac-liv', name: 'Liverpool', shortName: 'Liverpool', city: 'Liverpool' },
          { id: 'fac-mci', name: 'Manchester City', shortName: 'Man City', city: 'Manchester' },
          { id: 'fac-tot', name: 'Tottenham Hotspur', shortName: 'Spurs', city: 'London' },
          { id: 'fac-final', name: 'FA Cup Final', shortName: 'FA Cup Final' },
        ],
      },
      {
        id: 'efl-cup',
        name: 'EFL Cup (Carabao Cup)',
        country: 'England',
        kind: 'cup',
        teams: [
          { id: 'lc-liv', name: 'Liverpool', shortName: 'Liverpool', city: 'Liverpool' },
          { id: 'lc-mci', name: 'Manchester City', shortName: 'Man City', city: 'Manchester' },
          { id: 'lc-che', name: 'Chelsea', shortName: 'Chelsea', city: 'London' },
          { id: 'lc-new', name: 'Newcastle United', shortName: 'Newcastle', city: 'Newcastle' },
          { id: 'lc-final', name: 'Carabao Cup Final', shortName: 'Carabao Final' },
        ],
      },
      {
        id: 'copa-del-rey',
        name: 'Copa del Rey',
        country: 'Spain',
        kind: 'cup',
        teams: [
          { id: 'cdr-rm', name: 'Real Madrid', shortName: 'Real Madrid', city: 'Madrid' },
          { id: 'cdr-bar', name: 'FC Barcelona', shortName: 'Barça', city: 'Barcelona' },
          { id: 'cdr-atm', name: 'Atlético Madrid', shortName: 'Atleti', city: 'Madrid' },
          { id: 'cdr-ath', name: 'Athletic Club', shortName: 'Athletic', city: 'Bilbao' },
          { id: 'cdr-final', name: 'Copa del Rey Final', shortName: 'Copa Final' },
        ],
      },
      {
        id: 'dfb-pokal',
        name: 'DFB-Pokal',
        country: 'Germany',
        kind: 'cup',
        teams: [
          { id: 'dfb-bay', name: 'Bayern Munich', shortName: 'Bayern', city: 'Munich' },
          { id: 'dfb-dor', name: 'Borussia Dortmund', shortName: 'Dortmund', city: 'Dortmund' },
          { id: 'dfb-b04', name: 'Bayer Leverkusen', shortName: 'Leverkusen', city: 'Leverkusen' },
          { id: 'dfb-rb', name: 'RB Leipzig', shortName: 'Leipzig', city: 'Leipzig' },
          { id: 'dfb-final', name: 'DFB-Pokal Final', shortName: 'Pokal Final' },
        ],
      },
      {
        id: 'coppa-italia',
        name: 'Coppa Italia',
        country: 'Italy',
        kind: 'cup',
        teams: [
          { id: 'coi-juv', name: 'Juventus', shortName: 'Juve', city: 'Turin' },
          { id: 'coi-int', name: 'Inter Milan', shortName: 'Inter', city: 'Milan' },
          { id: 'coi-acm', name: 'AC Milan', shortName: 'Milan', city: 'Milan' },
          { id: 'coi-nap', name: 'Napoli', shortName: 'Napoli', city: 'Naples' },
          { id: 'coi-final', name: 'Coppa Italia Final', shortName: 'Coppa Final' },
        ],
      },
      {
        id: 'coupe-de-france',
        name: 'Coupe de France',
        country: 'France',
        kind: 'cup',
        teams: [
          { id: 'cdf-psg', name: 'Paris Saint-Germain', shortName: 'PSG', city: 'Paris' },
          { id: 'cdf-mar', name: 'Olympique de Marseille', shortName: 'Marseille', city: 'Marseille' },
          { id: 'cdf-lyn', name: 'Olympique Lyonnais', shortName: 'Lyon', city: 'Lyon' },
          { id: 'cdf-final', name: 'Coupe de France Final', shortName: 'Coupe Final' },
        ],
      },
      {
        id: 'fifa-world-cup',
        name: 'FIFA World Cup',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'wc-arg', name: 'Argentina', shortName: 'Argentina' },
          { id: 'wc-bra', name: 'Brazil', shortName: 'Brazil' },
          { id: 'wc-fra', name: 'France', shortName: 'France' },
          { id: 'wc-eng', name: 'England', shortName: 'England' },
          { id: 'wc-esp', name: 'Spain', shortName: 'Spain' },
          { id: 'wc-ger', name: 'Germany', shortName: 'Germany' },
          { id: 'wc-por', name: 'Portugal', shortName: 'Portugal' },
          { id: 'wc-ned', name: 'Netherlands', shortName: 'Netherlands' },
          { id: 'wc-ita', name: 'Italy', shortName: 'Italy' },
          { id: 'wc-bel', name: 'Belgium', shortName: 'Belgium' },
          { id: 'wc-cro', name: 'Croatia', shortName: 'Croatia' },
          { id: 'wc-uru', name: 'Uruguay', shortName: 'Uruguay' },
          { id: 'wc-usa', name: 'USA', shortName: 'USA' },
          { id: 'wc-mex', name: 'Mexico', shortName: 'Mexico' },
          { id: 'wc-jpn', name: 'Japan', shortName: 'Japan' },
          { id: 'wc-mar', name: 'Morocco', shortName: 'Morocco' },
          { id: 'wc-final', name: 'World Cup Final', shortName: 'WC Final' },
        ],
      },
      {
        id: 'euros',
        name: 'UEFA European Championship',
        country: 'Europe',
        kind: 'international',
        teams: [
          { id: 'euro-eng', name: 'England', shortName: 'England' },
          { id: 'euro-fra', name: 'France', shortName: 'France' },
          { id: 'euro-esp', name: 'Spain', shortName: 'Spain' },
          { id: 'euro-ger', name: 'Germany', shortName: 'Germany' },
          { id: 'euro-ita', name: 'Italy', shortName: 'Italy' },
          { id: 'euro-por', name: 'Portugal', shortName: 'Portugal' },
          { id: 'euro-ned', name: 'Netherlands', shortName: 'Netherlands' },
          { id: 'euro-bel', name: 'Belgium', shortName: 'Belgium' },
          { id: 'euro-cro', name: 'Croatia', shortName: 'Croatia' },
          { id: 'euro-final', name: 'Euro Final', shortName: 'Euro Final' },
        ],
      },
      {
        id: 'copa-america',
        name: 'Copa América',
        country: 'South America',
        kind: 'international',
        teams: [
          { id: 'ca-arg', name: 'Argentina', shortName: 'Argentina' },
          { id: 'ca-bra', name: 'Brazil', shortName: 'Brazil' },
          { id: 'ca-uru', name: 'Uruguay', shortName: 'Uruguay' },
          { id: 'ca-col', name: 'Colombia', shortName: 'Colombia' },
          { id: 'ca-chi', name: 'Chile', shortName: 'Chile' },
          { id: 'ca-per', name: 'Peru', shortName: 'Peru' },
          { id: 'ca-final', name: 'Copa América Final', shortName: 'Copa Final' },
        ],
      },
      {
        id: 'uefa-nations-league',
        name: 'UEFA Nations League',
        country: 'Europe',
        kind: 'international',
        teams: [
          { id: 'unl-esp', name: 'Spain', shortName: 'Spain' },
          { id: 'unl-fra', name: 'France', shortName: 'France' },
          { id: 'unl-por', name: 'Portugal', shortName: 'Portugal' },
          { id: 'unl-ger', name: 'Germany', shortName: 'Germany' },
          { id: 'unl-ned', name: 'Netherlands', shortName: 'Netherlands' },
          { id: 'unl-ita', name: 'Italy', shortName: 'Italy' },
          { id: 'unl-final', name: 'Nations League Finals', shortName: 'UNL Finals' },
        ],
      },
      {
        id: 'club-world-cup',
        name: 'FIFA Club World Cup',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'cwc-rm', name: 'Real Madrid', shortName: 'Real Madrid', city: 'Madrid' },
          { id: 'cwc-mci', name: 'Manchester City', shortName: 'Man City', city: 'Manchester' },
          { id: 'cwc-bay', name: 'Bayern Munich', shortName: 'Bayern', city: 'Munich' },
          { id: 'cwc-fla', name: 'Flamengo', shortName: 'Flamengo', city: 'Rio de Janeiro' },
          { id: 'cwc-final', name: 'Club World Cup Final', shortName: 'CWC Final' },
        ],
      },
      {
        id: 'copa-libertadores',
        name: 'Copa Libertadores',
        country: 'South America',
        kind: 'cup',
        teams: [
          { id: 'lib-boc', name: 'Boca Juniors', shortName: 'Boca', city: 'Buenos Aires' },
          { id: 'lib-riv', name: 'River Plate', shortName: 'River', city: 'Buenos Aires' },
          { id: 'lib-fla', name: 'Flamengo', shortName: 'Flamengo', city: 'Rio de Janeiro' },
          { id: 'lib-pal', name: 'Palmeiras', shortName: 'Palmeiras', city: 'São Paulo' },
          { id: 'lib-final', name: 'Libertadores Final', shortName: 'Libertadores Final' },
        ],
      },
    ],
  },

  // ─── Motorsport ───────────────────────────────────────────────────────────
  {
    id: 'motorsport',
    name: 'Motorsport',
    emoji: '🏎️',
    leagues: [
      {
        id: 'f1-2025',
        name: 'Formula 1',
        country: 'International',
        kind: 'league',
        teams: [
          { id: 'f1-alp', name: 'Alpine', shortName: 'Alpine' },
          { id: 'f1-ast', name: 'Aston Martin', shortName: 'Aston Martin' },
          { id: 'f1-fer', name: 'Ferrari', shortName: 'Ferrari' },
          { id: 'f1-haa', name: 'Haas', shortName: 'Haas' },
          { id: 'f1-kick', name: 'Kick Sauber', shortName: 'Sauber' },
          { id: 'f1-mcl', name: 'McLaren', shortName: 'McLaren' },
          { id: 'f1-mer', name: 'Mercedes', shortName: 'Mercedes' },
          { id: 'f1-rb', name: 'Racing Bulls', shortName: 'Racing Bulls' },
          { id: 'f1-rbr', name: 'Red Bull Racing', shortName: 'Red Bull' },
          { id: 'f1-wil', name: 'Williams', shortName: 'Williams' },
          { id: 'f1-monaco', name: 'Monaco Grand Prix', shortName: 'Monaco GP' },
          { id: 'f1-silver', name: 'British Grand Prix', shortName: 'British GP' },
        ],
      },
      {
        id: 'motogp',
        name: 'MotoGP',
        country: 'International',
        kind: 'league',
        teams: [
          { id: 'mgp-duc', name: 'Ducati', shortName: 'Ducati' },
          { id: 'mgp-apr', name: 'Aprilia', shortName: 'Aprilia' },
          { id: 'mgp-ktm', name: 'KTM', shortName: 'KTM' },
          { id: 'mgp-yam', name: 'Yamaha', shortName: 'Yamaha' },
          { id: 'mgp-hon', name: 'Honda', shortName: 'Honda' },
        ],
      },
      {
        id: 'nascar',
        name: 'NASCAR',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'nas-day', name: 'Daytona 500', shortName: 'Daytona 500' },
          { id: 'nas-cup', name: 'NASCAR Cup Series', shortName: 'Cup Series' },
          { id: 'nas-hen', name: 'Hendrick Motorsports', shortName: 'Hendrick' },
          { id: 'nas-pen', name: 'Team Penske', shortName: 'Penske' },
        ],
      },
      {
        id: 'indycar',
        name: 'IndyCar',
        country: 'USA',
        kind: 'league',
        teams: [
          { id: 'ind-500', name: 'Indianapolis 500', shortName: 'Indy 500' },
          { id: 'ind-pen', name: 'Team Penske', shortName: 'Penske' },
          { id: 'ind-gan', name: 'Chip Ganassi Racing', shortName: 'Ganassi' },
        ],
      },
    ],
  },

  // ─── Rugby Union ─────────────────────────────────────────────────────────
  {
    id: 'rugby-union',
    name: 'Rugby Union',
    emoji: '🏉',
    leagues: [
      {
        id: 'six-nations',
        name: 'Six Nations',
        country: 'Europe',
        kind: 'international',
        teams: [
          { id: 'eng-r', name: 'England', shortName: 'England' },
          { id: 'fra-r', name: 'France', shortName: 'France' },
          { id: 'ire-r', name: 'Ireland', shortName: 'Ireland' },
          { id: 'ita-r', name: 'Italy', shortName: 'Italy' },
          { id: 'sco-r', name: 'Scotland', shortName: 'Scotland' },
          { id: 'wal-r', name: 'Wales', shortName: 'Wales' },
        ],
      },
      {
        id: 'rugby-championship',
        name: 'The Rugby Championship',
        country: 'Southern Hemisphere',
        kind: 'international',
        teams: [
          { id: 'rc-nzl', name: 'New Zealand', shortName: 'All Blacks' },
          { id: 'rc-rsa', name: 'South Africa', shortName: 'Springboks' },
          { id: 'rc-aus', name: 'Australia', shortName: 'Wallabies' },
          { id: 'rc-arg', name: 'Argentina', shortName: 'Pumas' },
        ],
      },
      {
        id: 'rugby-wc',
        name: 'Rugby World Cup',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'arg-r', name: 'Argentina', shortName: 'Pumas' },
          { id: 'aus-r', name: 'Australia', shortName: 'Wallabies' },
          { id: 'nzl-r', name: 'New Zealand', shortName: 'All Blacks' },
          { id: 'rsa-r', name: 'South Africa', shortName: 'Springboks' },
          { id: 'sam-r', name: 'Samoa', shortName: 'Samoa' },
          { id: 'fij-r', name: 'Fiji', shortName: 'Fiji' },
          { id: 'jpn-r', name: 'Japan', shortName: 'Brave Blossoms' },
        ],
      },
      {
        id: 'champions-cup',
        name: 'Investec Champions Cup',
        country: 'Europe',
        kind: 'cup',
        teams: [
          { id: 'cc-lei', name: 'Leinster', shortName: 'Leinster', city: 'Dublin' },
          { id: 'cc-tou', name: 'Toulouse', shortName: 'Toulouse', city: 'Toulouse' },
          { id: 'cc-larr', name: 'La Rochelle', shortName: 'La Rochelle', city: 'La Rochelle' },
          { id: 'cc-nor', name: 'Northampton Saints', shortName: 'Northampton' },
          { id: 'cc-final', name: 'Champions Cup Final', shortName: 'Cup Final' },
        ],
      },
      {
        id: 'premiership-rugby',
        name: 'Premiership Rugby',
        country: 'England',
        kind: 'league',
        teams: [
          { id: 'bath-r', name: 'Bath Rugby', shortName: 'Bath' },
          { id: 'bri-r', name: 'Bristol Bears', shortName: 'Bristol' },
          { id: 'exe-r', name: 'Exeter Chiefs', shortName: 'Exeter' },
          { id: 'glo-r', name: 'Gloucester Rugby', shortName: 'Gloucester' },
          { id: 'har-r', name: 'Harlequins', shortName: 'Harlequins' },
          { id: 'lei-t', name: 'Leicester Tigers', shortName: 'Leicester' },
          { id: 'new-f', name: 'Newcastle Falcons', shortName: 'Newcastle' },
          { id: 'nor-s', name: 'Northampton Saints', shortName: 'Northampton' },
          { id: 'sal-r', name: 'Sale Sharks', shortName: 'Sale' },
        ],
      },
      {
        id: 'urc',
        name: 'United Rugby Championship',
        country: 'Europe/S. Africa',
        kind: 'league',
        teams: [
          { id: 'urc-lei', name: 'Leinster', shortName: 'Leinster', city: 'Dublin' },
          { id: 'urc-mun', name: 'Munster', shortName: 'Munster', city: 'Limerick' },
          { id: 'urc-gla', name: 'Glasgow Warriors', shortName: 'Glasgow' },
          { id: 'urc-sto', name: 'Stormers', shortName: 'Stormers', city: 'Cape Town' },
          { id: 'urc-bul', name: 'Bulls', shortName: 'Bulls', city: 'Pretoria' },
        ],
      },
      {
        id: 'lions-tour',
        name: 'British & Irish Lions',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'lions', name: 'British & Irish Lions', shortName: 'Lions' },
        ],
      },
    ],
  },

  // ─── Rugby League ────────────────────────────────────────────────────────
  {
    id: 'rugby-league',
    name: 'Rugby League',
    emoji: '🏉',
    leagues: [
      {
        id: 'nrl',
        name: 'NRL',
        country: 'Australia',
        kind: 'league',
        teams: [
          { id: 'nrl-pen', name: 'Penrith Panthers', shortName: 'Panthers', city: 'Penrith' },
          { id: 'nrl-mel', name: 'Melbourne Storm', shortName: 'Storm', city: 'Melbourne' },
          { id: 'nrl-bri', name: 'Brisbane Broncos', shortName: 'Broncos', city: 'Brisbane' },
          { id: 'nrl-syd', name: 'Sydney Roosters', shortName: 'Roosters', city: 'Sydney' },
          { id: 'nrl-sou', name: 'South Sydney Rabbitohs', shortName: 'Rabbitohs', city: 'Sydney' },
        ],
      },
      {
        id: 'super-league',
        name: 'Super League',
        country: 'England',
        kind: 'league',
        teams: [
          { id: 'sl-wig', name: 'Wigan Warriors', shortName: 'Wigan' },
          { id: 'sl-sth', name: 'St Helens', shortName: 'St Helens' },
          { id: 'sl-lee', name: 'Leeds Rhinos', shortName: 'Leeds' },
          { id: 'sl-hul', name: 'Hull FC', shortName: 'Hull FC' },
        ],
      },
      {
        id: 'state-of-origin',
        name: 'State of Origin',
        country: 'Australia',
        kind: 'international',
        teams: [
          { id: 'soo-nsw', name: 'New South Wales', shortName: 'NSW Blues' },
          { id: 'soo-qld', name: 'Queensland', shortName: 'QLD Maroons' },
        ],
      },
    ],
  },

  // ─── Cricket ─────────────────────────────────────────────────────────────
  {
    id: 'cricket',
    name: 'Cricket',
    emoji: '🏏',
    leagues: [
      {
        id: 'test-nations',
        name: 'Test Cricket',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'aus-c', name: 'Australia', shortName: 'Australia' },
          { id: 'ban-c', name: 'Bangladesh', shortName: 'Bangladesh' },
          { id: 'eng-c', name: 'England', shortName: 'England' },
          { id: 'ind-c', name: 'India', shortName: 'India' },
          { id: 'nzl-c', name: 'New Zealand', shortName: 'New Zealand' },
          { id: 'pak-c', name: 'Pakistan', shortName: 'Pakistan' },
          { id: 'rsa-c', name: 'South Africa', shortName: 'South Africa' },
          { id: 'lka-c', name: 'Sri Lanka', shortName: 'Sri Lanka' },
          { id: 'win-c', name: 'West Indies', shortName: 'West Indies' },
          { id: 'zim-c', name: 'Zimbabwe', shortName: 'Zimbabwe' },
          { id: 'ire-c', name: 'Ireland', shortName: 'Ireland' },
          { id: 'afg-c', name: 'Afghanistan', shortName: 'Afghanistan' },
        ],
      },
      {
        id: 'the-ashes',
        name: 'The Ashes',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'ash-eng', name: 'England', shortName: 'England' },
          { id: 'ash-aus', name: 'Australia', shortName: 'Australia' },
        ],
      },
      {
        id: 'cricket-world-cup',
        name: 'ICC World Cup (ODI)',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'cwc-ind', name: 'India', shortName: 'India' },
          { id: 'cwc-aus', name: 'Australia', shortName: 'Australia' },
          { id: 'cwc-eng', name: 'England', shortName: 'England' },
          { id: 'cwc-rsa', name: 'South Africa', shortName: 'South Africa' },
          { id: 'cwc-nzl', name: 'New Zealand', shortName: 'New Zealand' },
          { id: 'cwc-pak', name: 'Pakistan', shortName: 'Pakistan' },
        ],
      },
      {
        id: 't20-world-cup',
        name: 'ICC T20 World Cup',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 't20-ind', name: 'India', shortName: 'India' },
          { id: 't20-aus', name: 'Australia', shortName: 'Australia' },
          { id: 't20-eng', name: 'England', shortName: 'England' },
          { id: 't20-win', name: 'West Indies', shortName: 'West Indies' },
          { id: 't20-rsa', name: 'South Africa', shortName: 'South Africa' },
        ],
      },
      {
        id: 'ipl',
        name: 'IPL',
        country: 'India',
        kind: 'league',
        teams: [
          { id: 'csk', name: 'Chennai Super Kings', shortName: 'CSK', city: 'Chennai' },
          { id: 'dc-ipl', name: 'Delhi Capitals', shortName: 'DC', city: 'Delhi' },
          { id: 'gt-ipl', name: 'Gujarat Titans', shortName: 'GT', city: 'Gujarat' },
          { id: 'kkr', name: 'Kolkata Knight Riders', shortName: 'KKR', city: 'Kolkata' },
          { id: 'lsg', name: 'Lucknow Super Giants', shortName: 'LSG', city: 'Lucknow' },
          { id: 'mi-ipl', name: 'Mumbai Indians', shortName: 'MI', city: 'Mumbai' },
          { id: 'pbks', name: 'Punjab Kings', shortName: 'PBKS', city: 'Punjab' },
          { id: 'rr-ipl', name: 'Rajasthan Royals', shortName: 'RR', city: 'Rajasthan' },
          { id: 'rcb', name: 'Royal Challengers Bengaluru', shortName: 'RCB', city: 'Bengaluru' },
          { id: 'srh', name: 'Sunrisers Hyderabad', shortName: 'SRH', city: 'Hyderabad' },
        ],
      },
      {
        id: 'the-hundred',
        name: 'The Hundred',
        country: 'England',
        kind: 'league',
        teams: [
          { id: 'hun-loni', name: 'London Spirit', shortName: 'London Spirit' },
          { id: 'hun-ori', name: 'Oval Invincibles', shortName: 'Oval Invincibles' },
          { id: 'hun-tro', name: 'Trent Rockets', shortName: 'Trent Rockets' },
          { id: 'hun-bph', name: 'Birmingham Phoenix', shortName: 'Birmingham Phoenix' },
        ],
      },
      {
        id: 'bbl',
        name: 'Big Bash League',
        country: 'Australia',
        kind: 'league',
        teams: [
          { id: 'bbl-per', name: 'Perth Scorchers', shortName: 'Scorchers', city: 'Perth' },
          { id: 'bbl-syd-s', name: 'Sydney Sixers', shortName: 'Sixers', city: 'Sydney' },
          { id: 'bbl-syd-t', name: 'Sydney Thunder', shortName: 'Thunder', city: 'Sydney' },
          { id: 'bbl-mel-s', name: 'Melbourne Stars', shortName: 'Stars', city: 'Melbourne' },
        ],
      },
    ],
  },

  // ─── Tennis ───────────────────────────────────────────────────────────────
  {
    id: 'tennis',
    name: 'Tennis',
    emoji: '🎾',
    leagues: [
      {
        id: 'grand-slams',
        name: 'Grand Slams',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'ao', name: 'Australian Open', shortName: 'Aus Open' },
          { id: 'rg', name: 'Roland Garros', shortName: 'French Open' },
          { id: 'wimb', name: 'Wimbledon', shortName: 'Wimbledon' },
          { id: 'uso', name: 'US Open', shortName: 'US Open' },
        ],
      },
      {
        id: 'atp-tour',
        name: 'ATP Tour',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'atp-finals', name: 'ATP Finals', shortName: 'ATP Finals' },
          { id: 'atp-iw', name: 'Indian Wells Masters', shortName: 'Indian Wells' },
          { id: 'atp-miami', name: 'Miami Open', shortName: 'Miami Open' },
          { id: 'atp-monte', name: 'Monte-Carlo Masters', shortName: 'Monte-Carlo' },
        ],
      },
      {
        id: 'wta-tour',
        name: 'WTA Tour',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'wta-finals', name: 'WTA Finals', shortName: 'WTA Finals' },
          { id: 'wta-iw', name: 'Indian Wells Open', shortName: 'Indian Wells' },
        ],
      },
      {
        id: 'davis-cup',
        name: 'Davis Cup',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'dcup-final', name: 'Davis Cup Finals', shortName: 'Davis Cup' },
        ],
      },
    ],
  },

  // ─── Golf ─────────────────────────────────────────────────────────────────
  {
    id: 'golf',
    name: 'Golf',
    emoji: '⛳',
    leagues: [
      {
        id: 'majors',
        name: 'Majors',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'masters', name: 'The Masters', shortName: 'Masters' },
          { id: 'pga-c', name: 'PGA Championship', shortName: 'PGA' },
          { id: 'us-open-g', name: 'US Open', shortName: 'US Open' },
          { id: 'the-open', name: 'The Open Championship', shortName: 'The Open' },
        ],
      },
      {
        id: 'ryder-cup',
        name: 'Ryder Cup & Team Events',
        country: 'International',
        kind: 'international',
        teams: [
          { id: 'ryder', name: 'Ryder Cup', shortName: 'Ryder Cup' },
          { id: 'presidents', name: 'Presidents Cup', shortName: 'Presidents Cup' },
          { id: 'solheim', name: 'Solheim Cup', shortName: 'Solheim Cup' },
        ],
      },
      {
        id: 'pga-tour',
        name: 'PGA Tour',
        country: 'USA',
        kind: 'cup',
        teams: [
          { id: 'pgat-players', name: 'The Players Championship', shortName: 'The Players' },
          { id: 'pgat-fedex', name: 'FedEx Cup / Tour Championship', shortName: 'FedEx Cup' },
        ],
      },
      {
        id: 'liv-golf',
        name: 'LIV Golf',
        country: 'International',
        kind: 'league',
        teams: [
          { id: 'liv-league', name: 'LIV Golf League', shortName: 'LIV Golf' },
        ],
      },
    ],
  },

  // ─── Combat Sports ────────────────────────────────────────────────────────
  {
    id: 'combat',
    name: 'Boxing & MMA',
    emoji: '🥊',
    leagues: [
      {
        id: 'ufc',
        name: 'UFC',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'ufc-ppv', name: 'UFC Pay-Per-View', shortName: 'UFC PPV' },
          { id: 'ufc-fight-night', name: 'UFC Fight Night', shortName: 'Fight Night' },
          { id: 'ufc-hw', name: 'UFC Heavyweight', shortName: 'HW' },
          { id: 'ufc-lhw', name: 'UFC Light Heavyweight', shortName: 'LHW' },
          { id: 'ufc-mw', name: 'UFC Middleweight', shortName: 'MW' },
          { id: 'ufc-ww', name: 'UFC Welterweight', shortName: 'WW' },
          { id: 'ufc-lw', name: 'UFC Lightweight', shortName: 'LW' },
          { id: 'ufc-fw', name: 'UFC Featherweight', shortName: 'FW' },
        ],
      },
      {
        id: 'boxing',
        name: 'Boxing',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'box-hw', name: 'Heavyweight Championship', shortName: 'Heavyweight' },
          { id: 'box-title', name: 'World Title Fight', shortName: 'Title Fight' },
          { id: 'box-ppv', name: 'Boxing Pay-Per-View', shortName: 'Boxing PPV' },
        ],
      },
      {
        id: 'other-mma',
        name: 'PFL & Bellator',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'pfl', name: 'PFL', shortName: 'PFL' },
          { id: 'bellator', name: 'Bellator MMA', shortName: 'Bellator' },
        ],
      },
    ],
  },

  // ─── Esports ──────────────────────────────────────────────────────────────
  {
    id: 'esports',
    name: 'Esports',
    emoji: '🎮',
    leagues: [
      {
        id: 'lol',
        name: 'League of Legends',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'lol-worlds', name: 'LoL World Championship', shortName: 'Worlds' },
          { id: 'lol-msi', name: 'Mid-Season Invitational', shortName: 'MSI' },
          { id: 'lol-lec', name: 'LEC (Europe)', shortName: 'LEC' },
          { id: 'lol-lcs', name: 'LCS (North America)', shortName: 'LCS' },
          { id: 'lol-lck', name: 'LCK (Korea)', shortName: 'LCK' },
        ],
      },
      {
        id: 'cs2',
        name: 'Counter-Strike 2',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'cs-major', name: 'CS2 Major', shortName: 'CS Major' },
          { id: 'cs-blast', name: 'BLAST Premier', shortName: 'BLAST' },
          { id: 'cs-esl', name: 'ESL Pro League', shortName: 'ESL' },
        ],
      },
      {
        id: 'valorant',
        name: 'Valorant',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'val-champs', name: 'Valorant Champions', shortName: 'Champions' },
          { id: 'val-masters', name: 'VCT Masters', shortName: 'Masters' },
        ],
      },
      {
        id: 'dota',
        name: 'Dota 2',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'dota-ti', name: 'The International', shortName: 'TI' },
        ],
      },
    ],
  },

  // ─── Cycling ──────────────────────────────────────────────────────────────
  {
    id: 'cycling',
    name: 'Cycling',
    emoji: '🚴',
    leagues: [
      {
        id: 'grand-tours',
        name: 'Grand Tours',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'tdf', name: 'Tour de France', shortName: 'Tour de France' },
          { id: 'giro', name: "Giro d'Italia", shortName: "Giro d'Italia" },
          { id: 'vuelta', name: 'Vuelta a España', shortName: 'Vuelta' },
        ],
      },
      {
        id: 'classics',
        name: 'Monuments & Classics',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'cyc-prb', name: 'Paris-Roubaix', shortName: 'Paris-Roubaix' },
          { id: 'cyc-mss', name: 'Milan-San Remo', shortName: 'Milan-San Remo' },
          { id: 'cyc-flanders', name: 'Tour of Flanders', shortName: 'Flanders' },
        ],
      },
    ],
  },

  // ─── Darts & Snooker ──────────────────────────────────────────────────────
  {
    id: 'cue-and-darts',
    name: 'Darts & Snooker',
    emoji: '🎯',
    leagues: [
      {
        id: 'pdc-darts',
        name: 'PDC Darts',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'darts-worlds', name: 'PDC World Championship', shortName: 'Worlds' },
          { id: 'darts-premier', name: 'Premier League Darts', shortName: 'Premier League' },
          { id: 'darts-matchplay', name: 'World Matchplay', shortName: 'Matchplay' },
        ],
      },
      {
        id: 'snooker',
        name: 'Snooker',
        country: 'International',
        kind: 'cup',
        teams: [
          { id: 'snk-worlds', name: 'World Snooker Championship', shortName: 'Worlds' },
          { id: 'snk-uk', name: 'UK Championship', shortName: 'UK Champ' },
          { id: 'snk-masters', name: 'The Masters', shortName: 'Masters' },
        ],
      },
    ],
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getAllTeams(): Team[] {
  return SPORTS.flatMap((s) => s.leagues.flatMap((l) => l.teams));
}

export function searchTeams(query: string): Array<Team & { sportName: string; leagueName: string }> {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  const results: Array<Team & { sportName: string; leagueName: string }> = [];
  for (const sport of SPORTS) {
    for (const league of sport.leagues) {
      for (const team of league.teams) {
        if (team.name.toLowerCase().includes(q) || team.shortName.toLowerCase().includes(q)) {
          results.push({ ...team, sportName: sport.name, leagueName: league.name });
        }
      }
    }
  }
  return results.slice(0, 50);
}

export function getSportById(id: string): Sport | undefined {
  return SPORTS.find((s) => s.id === id);
}

export function getTeamById(id: string): (Team & { sport: Sport; league: League }) | undefined {
  for (const sport of SPORTS) {
    for (const league of sport.leagues) {
      const team = league.teams.find((t) => t.id === id);
      if (team) return { ...team, sport, league };
    }
  }
  return undefined;
}
