// Generated by `wrangler types`; do not edit by hand.
// Run `npm run cf-typegen` after adding bindings to wrangler.jsonc.
interface Env {
  DATABASE_URL: string;
  BETTER_AUTH_URL?: string;
  RESEND_API_KEY?: string;
  ADMIN_SECRET?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  CHAT_ROOMS: DurableObjectNamespace;
  SPOTSEEK_IMAGES: R2Bucket;
}
